spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm:
  admin-user:
    id: supervisor
    password: supervisor
  filter:
    create: All tasks
  webapp:
    index-redirect-enabled: true